import { useState, useMemo } from 'react';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { PatientLayout } from '../../layouts/PatientLayout';
import { Card } from '../../components/common/Card';
import { LoadingState } from '../../components/common/LoadingState';
import { usePromTests } from '../usePromTests';
import { generateAnalysisReport } from '../../api/analysisReport';
import type { PromTestRead } from '../../api/promTests';
import {
  getDataCollectionConsent,
  getOrCreateVisitorPatientId,
} from '../utils/visitorIdentity';
import { promQuestions, scaleLabels } from '../promQuestions';

function AnalysisContent({
  analysisText,
  promTests,
  generatedAt,
}: {
  analysisText: string;
  promTests: PromTestRead[];
  generatedAt: string;
}) {
  const getAvg = (test: PromTestRead) => {
    const sum =
      test.q1 + test.q2 + test.q3 + test.q4 + test.q5 +
      test.q6 + test.q7 + test.q8 + test.q9 + test.q10;
    return (sum / 10).toFixed(1);
  };

  const analysisHtml = useMemo(
    () => DOMPurify.sanitize(marked.parse(analysisText) as string),
    [analysisText]
  );

  return (
    <div id="analysis-printable" className="space-y-6">
      {/* Header */}
      <div className="text-center border-b border-border-subtle pb-4">
        <h1 className="text-2xl font-bold text-text-main">Patient Analysis Report</h1>
        <p className="text-sm text-text-muted mt-1">
          Deep Brain Stimulation — Patient-Reported Outcome Summary
        </p>
        <p className="text-xs text-text-muted mt-1">Generated: {generatedAt}</p>
      </div>

      {/* AI Analysis */}
      <Card className="p-6">
        <h2 className="text-lg font-semibold text-text-main mb-3">AI Clinical Summary</h2>
        <div
          className="markdown-content text-text-main"
          dangerouslySetInnerHTML={{ __html: analysisHtml }}
        />
        <p className="text-xs text-text-muted mt-4 italic">
          This summary was generated by an AI assistant and is intended to support, not replace,
          professional clinical judgment.
        </p>
      </Card>

      {/* PROM History table */}
      {promTests.length > 0 && (
        <Card className="p-6">
          <h2 className="text-lg font-semibold text-text-main mb-3">Assessment History</h2>
          <div className="overflow-x-auto">
            <table className="w-full text-xs border-collapse">
              <thead>
                <tr className="border-b-2 border-border-subtle">
                  <th className="text-left py-2 px-2 font-semibold text-text-main">Date</th>
                  {promQuestions.map((q) => (
                    <th key={q.id} className="text-center py-2 px-1 font-semibold text-text-main">
                      {q.id.toUpperCase()}
                    </th>
                  ))}
                  <th className="text-center py-2 px-2 font-semibold text-text-main">Avg</th>
                </tr>
              </thead>
              <tbody>
                {promTests.map((test) => (
                  <tr key={test.id} className="border-b border-border-subtle">
                    <td className="py-2 px-2 text-text-main font-medium">
                      {new Date(test.testDate).toLocaleDateString()}
                    </td>
                    {promQuestions.map((q) => (
                      <td key={q.id} className="text-center py-2 px-1 text-text-main">
                        {test[q.id]}
                      </td>
                    ))}
                    <td className="text-center py-2 px-2 font-semibold text-brand-blue">
                      {getAvg(test)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {/* Score legend */}
          <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1">
            {Object.entries(scaleLabels).map(([score, label]) => (
              <span key={score} className="text-xs text-text-muted">
                {score} = {label}
              </span>
            ))}
          </div>
          {/* Question legend */}
          <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1">
            {promQuestions.map((q) => (
              <p key={q.id} className="text-xs text-text-muted">
                <span className="font-semibold">{q.id.toUpperCase()}:</span> {q.label}
              </p>
            ))}
          </div>
        </Card>
      )}
    </div>
  );
}

export function PatientAnalysisReportPage() {
  const consent = getDataCollectionConsent();
  const patientId = consent === 'approved' ? getOrCreateVisitorPatientId() : null;

  const { tests, loading: testsLoading, error: testsError } = usePromTests(patientId);

  const [analysisText, setAnalysisText] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string>('');
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!patientId || tests.length === 0) return;

    setGenerating(true);
    setGenerateError(null);

    try {
      const promData = tests.map((t) => ({
        test_date: t.testDate,
        q1: t.q1,
        q2: t.q2,
        q3: t.q3,
        q4: t.q4,
        q5: t.q5,
        q6: t.q6,
        q7: t.q7,
        q8: t.q8,
        q9: t.q9,
        q10: t.q10,
      }));

      const result = await generateAnalysisReport({ patient_id: patientId, prom_data: promData });
      setAnalysisText(result.analysis_text);
      setGeneratedAt(new Date().toLocaleString());
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to generate report';
      setGenerateError(msg);
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (!patientId) {
    return (
      <PatientLayout>
        <div className="px-8 py-6 max-w-3xl mx-auto">
          <Card className="p-6 text-center">
            <h2 className="text-lg font-semibold text-text-main">Data collection required</h2>
            <p className="text-text-muted text-sm mt-1">
              Please approve data collection on the Daily Report page before generating an analysis.
            </p>
          </Card>
        </div>
      </PatientLayout>
    );
  }

  return (
    <>
      {/* Print-only styles */}
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #analysis-printable, #analysis-printable * { visibility: visible; }
          #analysis-printable { position: absolute; left: 0; top: 0; width: 100%; }
        }
      `}</style>

      <PatientLayout>
        <div className="px-8 py-6">
          <div className="max-w-3xl mx-auto space-y-6">
            <div className="text-center">
              <h1 className="text-3xl font-bold text-text-main">Analysis Report</h1>
              <p className="text-text-muted text-base mt-2">
                Generate an AI-powered summary of your assessment data to share with your doctor.
              </p>
            </div>

            {testsLoading && (
              <Card className="p-6">
                <LoadingState />
              </Card>
            )}

            {testsError && (
              <Card className="p-6 text-center">
                <p className="text-red-600 text-sm">{testsError}</p>
              </Card>
            )}

            {!testsLoading && !testsError && tests.length === 0 && (
              <Card className="p-6 text-center">
                <h2 className="text-lg font-semibold text-text-main">No assessments found</h2>
                <p className="text-text-muted text-sm mt-1">
                  Complete at least one daily report before generating an analysis.
                </p>
              </Card>
            )}

            {!testsLoading && !testsError && tests.length > 0 && !analysisText && (
              <Card className="p-6">
                <p className="text-sm text-text-muted mb-4">
                  {tests.length} assessment(s) found. Click the button below to generate a
                  personalized AI summary you can share with your doctor.
                </p>
                {generateError && (
                  <p className="text-red-600 text-sm mb-3">{generateError}</p>
                )}
                <button
                  type="button"
                  onClick={handleGenerate}
                  disabled={generating}
                  className="rounded-sm bg-brand-blue px-4 py-2 text-sm font-semibold text-white hover:bg-brand-navy disabled:opacity-60"
                >
                  {generating ? 'Generating…' : 'Generate Analysis'}
                </button>
              </Card>
            )}

            {analysisText && (
              <>
                <div className="flex justify-end gap-3">
                  <button
                    type="button"
                    onClick={handleGenerate}
                    disabled={generating}
                    className="rounded-sm border border-border-subtle bg-surface px-4 py-2 text-sm font-semibold text-text-main hover:border-brand-blue disabled:opacity-60"
                  >
                    {generating ? 'Regenerating…' : 'Regenerate'}
                  </button>
                  <button
                    type="button"
                    onClick={handlePrint}
                    className="rounded-sm bg-brand-blue px-4 py-2 text-sm font-semibold text-white hover:bg-brand-navy"
                  >
                    Save as PDF
                  </button>
                </div>

                <AnalysisContent
                  analysisText={analysisText}
                  promTests={tests}
                  generatedAt={generatedAt}
                />
              </>
            )}
          </div>
        </div>
      </PatientLayout>
    </>
  );
}
